### ISSUE TITLE
Exercises errors

### ISSUE THREAD

**Issue by rigwild** [nan-academy/js-training#8]
I noticed some errors in the exercises, did not go through all of them though.

Incorrect answer required in `same-sign.js` : 

`assert.strictEqual(sameSign(0, 231), false)`

Incorrect exercice statement (bad copy/paste from `max.js`  😉 ) in `min.js` :

> Create the 'min' function that takes 2 number as arguments and returns the **greatest**

The exercices are simple and easy to understand, i will pass them to my DUT's friends who want to learn js.
(I'm one of your french youtube subscriber!)

**Comment by kigiri** [comment]
Thank you for your help.

Nice catch on the copy / paste mistake, but for the sameSign, i'm afraid this is not a mistake.

`0` sign is `0` not `1` (you can try it with the standard `Math.sign(0)`)
However `231` sign is `1`, as such they are not equals.
```js
Math.sign(0) === Math.sign(231)
// computes to:
0 === 1
// which is strictly equal to false
```

**Comment by rigwild** [comment]
Thanks for clarification !
